# Generated by Django 5.2 on 2025-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
